###########################
### AddExpense endpoint ###
###########################

# Add new expense: all fields
POST http://127.0.0.1:5000/expenses HTTP/1.1
Content-Type: application/json

{"amount" : 20, "category": "misc", "description" : "Lorem Ipsum", "date" : "2025-01-20"}

###

# Add new expense: only mandatory fields
POST http://127.0.0.1:5000/expenses HTTP/1.1
Content-Type: application/json

{"amount" : 15, "category": "misc"}

###

# Add new expense: amount, category and description
POST http://127.0.0.1:5000/expenses HTTP/1.1
Content-Type: application/json

{"amount" : 10, "category": "misc", "description": "Lorem Ipsum 2"}

###

# Add new expense: amount, category and date
POST http://127.0.0.1:5000/expenses HTTP/1.1
Content-Type: application/json

{"amount" : 10, "category": "misc", "date": "2025-02-23"}

############################
### GetExpenses endpoint ###
############################

# Get all the expenses for the given date interval
GET http://127.0.0.1:5000/expenses?start_date=2025-03-01&end_date=2025-03-31 HTTP/1.1

###

# Get all the expenses from start_date onwards
GET http://127.0.0.1:5000/expenses?start_date=2023-02-01 HTTP/1.1

###############################
### DeleteExpenses endpoint ###
###############################

# Delete an expense given its id
DELETE http://127.0.0.1:5000/expenses/67cc87d81151765184fa5623 HTTP/1.1
